### PR TITLE
integrate keras models into training pipeline

### PR DESCRIPTION
**Pull request by ahundt**
based on:
https://github.com/warmspringwinds/tf-image-segmentation/pull/1

### CODE REVIEW

**Comment by ahundt** [comment]
@warmspringwinds could these changes be merged? they are working now

**Comment by warmspringwinds** [comment]
@ahundt . Give me sometime to review it first.

**Comment by BrianOn99** [comment]
In `mscoco_json2seg_mask.ipynb`, there is a variable `anns` never defined but used once.
@ahundt Are you sure the scripts are working or I miss something?

**Comment by ahundt** [comment]
@BrianOn99 don't use the ipynb, that's from changes that aren't mine. Also, note that the coco code  puts everything into a single layer, while the actual labeling has overlapping data. http://mscoco.org/explore/?id=21079 is an example, and that would need to be resolved to get the results you're hoping for. One simple improvement would be putting tables walls at the end of the z buffer list and moving small stuff like cups plates etc to the front.

Or help the ongoing work in https://github.com/PavlosMelissinos/enet-keras/ for mscoco (also not ready for prime time).

**Comment by ahundt** [comment]
#25 replaces this.

**Pull request closed without merging**
